<?php


/**
 * Author: Amir Hossein Jahani | iAmir.net
 * Last modified: 2/2/21, 8:13 AM
 * Copyright (c) 2021. Powered by iamir.net
 */

namespace iLaravel\Core\Providers;

//use Illuminate\Support\Facades\Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Gate;

class AuthServiceProvider extends ServiceProvider
{
    protected $policies = [
        // 'App\Model' => 'App\Policies\ModelPolicy',
    ];
    public function boot()
    {
        $this->registerPolicies();

        if (class_exists(\Laravel\Passport\Passport::class)) {
            \Laravel\Passport\Passport::withoutCookieSerialization();
            // Set expire date
            \Laravel\Passport\Passport::tokensExpireIn(now()->addDays(15));
            \Laravel\Passport\Passport::refreshTokensExpireIn(now()->addDays(30));
            \Laravel\Passport\Passport::personalAccessTokensExpireIn(now()->addMonths(6));
        }

        Gate::resource('users', 'iLaravel\Core\iApp\Policies\UserPolicy');
        Gate::resource('users.scopes', 'iLaravel\Core\iApp\Policies\UserScopePolicy');
        Gate::resource('roles', 'iLaravel\Core\iApp\Policies\RolePolicy');
        Gate::resource('roles.scopes', 'iLaravel\Core\iApp\Policies\RoleScopePolicy');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        Config::set([
            'auth.guards.api.driver' => 'passport'
        ]);
        Config::set([
            'auth.guards.apiIf' => array_merge(Config::get('auth.guards.api'), ['driver' => 'passport'])
        ]);
    }
}
