<?php
namespace iLaravel\Core\iApp\Http\Registrars;
use Illuminate\Routing\ResourceRegistrar as OriginalRegistrar;

class ResourceRegistrar extends OriginalRegistrar
{
    /**
     * The default actions for a resourceful controller.
     *
     * @var array
     */
    protected $resourceDefaults =  ['index', 'data', 'create', 'store', 'show', 'edit', 'update', 'destroy'];

    /**
     * Get the applicable resource methods.
     *
     * @param  array  $defaults
     * @param  array  $options
     * @return array
     */
    protected function getResourceMethods($defaults, $options)
    {
        if (isset($options['as']) &&  strpos($options['as'], 'api') !== false && $options['only'] && (!isset($options['except']) || isset($options['except']) && !in_array('index', $options['except']))){
            $options['only'][] = 'data';
        }
        return parent::getResourceMethods($defaults, $options); // TODO: Change the autogenerated stub
    }

    /**
     * Add the data method for a resourceful route.
     *
     * @param  string  $name
     * @param  string  $base
     * @param  string  $controller
     * @param  array   $options
     * @return \Illuminate\Routing\Route
     */
    protected function addResourceData($name, $base, $controller, $options)
    {
        $icontroller = iapicontroller($controller);
        $uri = $this->getResourceUri($name) . '/data';
        $action = $this->getResourceAction($name, $controller, method_exists($icontroller, 'data') ? 'data' : 'index', $options);

        return $this->router->get($uri, $action);
    }

    /**
     * Get the action array for a resource route.
     *
     * @param  string  $resource
     * @param  string  $controller
     * @param  string  $method
     * @param  array   $options
     * @return array
     */
    protected function getResourceAction($resource, $controller, $method, $options)
    {
        $name = $this->getResourceRouteName($resource, $method, $options);

        $action = ['as' => $name, 'uses' => $controller.'@'.$method, 'method' => $method];

        if (isset($options['middleware'])) {
            $action['middleware'] = $options['middleware'];
        }

        return $action;
    }
}
